### ISSUE TITLE
No pairing

### ISSUE THREAD

**Issue by gvansanden** [hannesschulze/conecto#14]
Installed fine on Juno, but I don't see my phone to pair, nor this app on kde connect on the phone...
Using kde connect does pair, but still the phone does not show up here.

**Comment by rajsardhara** [comment]
The issue is related to version backport, I fixed it by installing this first then install Connecto.

https://github.com/bboozzoo/mconnect

**Comment by hannesschulze** [comment]
See https://github.com/hannesschulze/conecto/issues/12#issuecomment-607424726
