### ISSUE TITLE
Proper icon

### ISSUE THREAD

**Issue by hannesschulze** [hannesschulze/conecto#2]
Don't use a system icon as the app icon

**Comment by Hedronmx** [comment]
Im glad you are back to working on this project! Ill see if I can create a cool icon

**Comment by Fatih20** [comment]
@hannesschulze What icon do you need? If you're looking for help, I could help you.

**Comment by hannesschulze** [comment]
I don’t know if you’ve seen this, but @Hedronmx has just offered to put together an icon and I feel like having two separate proposals right now would be more ineffective and unproductive than having one and steadily improving it if necessary. However, thank you to both of you for offering your help with this :)

**Comment by Hedronmx** [comment]
Its always good to have two options! @Fatih20 he is looking for the main app icon!

**Comment by Hedronmx** [comment]
@Fatih20 I thought I remembered you! I now  know, you designed the envelope icon. That is a really good icon. I guess you are more qualified for this job than I am.

**Comment by Fatih20** [comment]
Didn't think I was going to be recognized. I'll jump right into it then!

**Comment by hannesschulze** [comment]
Ok, great that you found a solution :)

**Comment by Fatih20** [comment]
So here's my initial suggestion for the icon.
![image](https://user-images.githubusercontent.com/51940383/78473387-8338d500-776a-11ea-9f30-9276f5545fda.png)
Here's how it looked like in the dock.
![image](https://user-images.githubusercontent.com/51940383/78473383-77e5a980-776a-11ea-98df-7b7e2dccbadb.png)
There're also ideas I threw in the trash.
![image](https://user-images.githubusercontent.com/51940383/78473412-aebbbf80-776a-11ea-86ed-a871205ae626.png)

Here's the thing tho. I feel like the first image I sent you is not really that good. I have an idea to instead of attempting to literally "symbolize" the core essence of what conecto is into an icon, Maybe I should take a more figurative approach.

Example of this is how the icon of simplenote doesn't contain an actual notebook 
or pencil. 

Let me know what you think.

**Comment by hannesschulze** [comment]
Thanks for your design! However there's one thing that is kind of misleading imo: Conecto is connecting to the device over the local WiFi network, not via USB. I feel like this symbol might be confusing to new users who find this app on App Center and don't read the full description and don't really know KDE Connect's concept already.

If we would go for more of a skeuomorphic approach like this one, I think it would be good to instead incorporate a symbol representing the wireless connection instead of the USB cable.

However I would also be really interested in this figurative approach you wrote about. Do you have something in mind for that yet?

**Comment by Fatih20** [comment]
I did. But I thought this app works via USB so I'll have to rework the ideas.

**Comment by Fatih20** [comment]
![image](https://user-images.githubusercontent.com/51940383/78668564-13ab1d00-7905-11ea-85f3-200f21fdf3ff.png)
What do you think? This icon is more general-purpose but convey the idea of the apps better, IMHO.

**Comment by hannesschulze** [comment]
That's looking great, I like it! :) I think you can already prepare the other sizes, if you don't have anything you want to change right now.

One more thing: If you have the other sizes ready and want to open a PR, could you please base the branch on `rewrite`? Since that is the one I'm currently merging all PRs into until I have the rewrite ready.

**Comment by Fatih20** [comment]
Okay, sure.

**Comment by Fatih20** [comment]
Just so you know I tweaked the icon a little bit and here's how it looked like on the dock right now. Will immediately pixel fit these and make a PR.
![image](https://user-images.githubusercontent.com/51940383/78897440-5eab6880-7a9c-11ea-8b97-865d3c524b1a.png)

**Comment by Fatih20** [comment]
After additional testing and tweaking, I've found that the icon I just made looked more like locking a phone (due to the chain) instead of connecting to a phone. I'll be starting from scratch, expect some setbacks.

**Comment by zelcion** [comment]
I don't know if the "entries" are open still, but here'e my take. I followed the icon colors and guidelines from Elementary os, so it should fit right in!
![logoconecto_g](https://user-images.githubusercontent.com/13098424/79622512-eb35d680-80ed-11ea-84b6-4f93abe17af9.png)

How it looks in the dock: 
![Screenshot from 2020-04-17 20-59-07](https://user-images.githubusercontent.com/13098424/79622633-69927880-80ee-11ea-8268-e6dd7def8ca3.png)

**Comment by Fatih20** [comment]
@flgmjr IMHO, I think that'd be extremely hard to pixel fit for 32-16 pixel size. This is in https://elementary.io/docs/human-interface-guidelines#dos-donts where overcomplication should be avoided.

**Comment by zelcion** [comment]
Yeah, your concerns are right, reducing it to 16px gets it a lot wonky
![logoconecto_s](https://user-images.githubusercontent.com/13098424/79625655-cbf47480-8100-11ea-8ac7-cc40104900d0.png)

32px and onwards is fine I guess. 
![logoconecto_ms](https://user-images.githubusercontent.com/13098424/79625719-33122900-8101-11ea-818d-5b0d5ca6546a.png)

Maybe for the really small something like this would be fine. Wdyt? @Fatih20 
![logoconecto_s_2](https://user-images.githubusercontent.com/13098424/79625892-7d47da00-8102-11ea-812b-5f067f7b104e.png)

**Comment by Fatih20** [comment]
I think that the use of letters aren't good in icon design because it has tendencies to just be a jumbled mess. IMO, It's either all letter like the icon of Adobe's software or objects only.

**Comment by zelcion** [comment]
I see that, maybe for different purposes it would work. In a logo (which i am much more used to do) it's usually no big deal, but when dealing with icons, mainly on small versions, there is no much space for readability so we have to abstract our intents in a tiny canvas, which turns out to be barely impossible with letters.

Probably some smart use of the arrows and phone might be enough for this case. Thanks for your input, helped me to identify where it could be better.

**Comment by zelcion** [comment]
By the way, here's the files, let's improve it!
[icons.zip](https://github.com/hannesschulze/conecto/files/4495956/icons.zip)

**Comment by Fatih20** [comment]
Right, so I did rework my original idea and moved to arrow, like @flgmjr said. And the results look surprisingly good.
![image](https://user-images.githubusercontent.com/51940383/79714141-1c82f200-82fa-11ea-903a-daf34b0db4b3.png)
![image](https://user-images.githubusercontent.com/51940383/79714162-27d61d80-82fa-11ea-830b-f322d21ead27.png)
![image](https://user-images.githubusercontent.com/51940383/79714177-33294900-82fa-11ea-8a9c-96921f7da574.png)

**Comment by Fatih20** [comment]
So here's my play with arrows and phone like @flgmjr said.
![image](https://user-images.githubusercontent.com/51940383/79715850-1e9b7f80-82ff-11ea-9273-a65ace688f89.png)
![image](https://user-images.githubusercontent.com/51940383/79715874-2f4bf580-82ff-11ea-80dd-1d22b0973f16.png)
![image](https://user-images.githubusercontent.com/51940383/79716015-8fdb3280-82ff-11ea-9d1d-4eb7699a7fdf.png)

**Comment by hannesschulze** [comment]
Hey, thanks for this new design, I like the idea :)

One thing I've noticed is that this icon looks pretty similar to the shape of an 'N' for smaller sizes (e.g. in the dock). Is there any way to move the two arrows a bit further apart to make it clearer?

**Comment by Fatih20** [comment]
Yes, of course. I thought the 'N' might actually be a play on your software's name. If you don't like it looking like an 'N' I'll change it up.

**Comment by hannesschulze** [comment]
Thanks, I think I would prefer not having the “N” there because it is not really the most fitting letter related to “Conecto” imo :)

**Comment by zelcion** [comment]
Maybe just shifting their sides is enough to do this, gold arrow on right, silver on left.

**Comment by Fatih20** [comment]
I don't know, I think the gold one higher than the silver is better.

**Comment by Fatih20** [comment]
Changed it to this. I'll be immediately pixel fitting them if you're fine with it.
![image](https://user-images.githubusercontent.com/51940383/80294204-1b861080-8791-11ea-9bc2-a35719aec829.png)

**Comment by hannesschulze** [comment]
That looks nice, thank you! :)

**Comment by hannesschulze** [comment]
Fixed in #26
