### ISSUE TITLE
Device not recognized

### ISSUE THREAD

**Issue by lohacker10** [hannesschulze/conecto#22]
I installed conecto on my pc and KDE Connect on my Android but neither pc nor phone are recognized. Why?

**Comment by hannesschulze** [comment]
From which branch did you install Conecto?

Conecto is currently in the process of a major rewrite, so I wouldn't recommend using it for production right now :D

- `master` contains the "old" Conecto, written in Vala and using an outdated version of mconnect
- `rewrite` contains the "new" Conecto, written in C++ and using a custom library for communication; however it is still missing a lot of plugins (see #16) and a proper UI (in progress, see #3)

**Comment by lohacker10** [comment]
Ok thanks I'm waiting the "new" Conecto! How can I uninstall the old version installed manually?

**Comment by hannesschulze** [comment]
You can do `sudo ninja uninstall` from the `build` directory
