### ISSUE TITLE
Connection times out after some time

### ISSUE THREAD

**Issue by sprite-1** [hannesschulze/conecto#4]
If I leave the app running in the background, it eventually loses connection to the phone. Here's a log of the whole affair from the app startup to it eventually timing out.

https://gist.github.com/sprite-1/4e71e18e11851591dd13920343d5f18e

**Comment by hannesschulze** [comment]
Ok, it seems like it overwrites the paired-status when it shouldn't.

One more thing: Could you please run it with `G_MESSAGES_DEBUG=all com.github.hannesschulze.conecto` until it happens and post that output? You can remove notifications if there are any during that time of course :)

**Comment by sprite-1** [comment]
I did that but the result is still the same as the previous log, but of course with a different time stamp

**Comment by hannesschulze** [comment]
See https://github.com/hannesschulze/conecto/issues/12#issuecomment-607424726
