### ISSUE TITLE
Crash on trying to connect with TLS handshake failure

### ISSUE THREAD

**Issue by maulwurf87** [hannesschulze/conecto#6]
Conecto crashes when trying to connect to the phone. It is rejecting the handshake because of a certificate mismatch. Could be solvable by a correct certificate.

This is the complete output from start to crash:
[tls-error-log.txt](https://github.com/hannesschulze/conecto/files/2821848/tls-error-log.txt)

**Comment by hannesschulze** [comment]
See https://github.com/hannesschulze/conecto/issues/12#issuecomment-607424726
