### ISSUE TITLE
Nothing shows up inside the window. It is not like screenshots.

### ISSUE THREAD

**Issue by ermanyurdakan** [hannesschulze/conecto#9]
Sorry if it is not the way I should ask about my issue. I am still a noob in GitHub and Linux world.

I did what the installation says and by that I mean I just copy-paste every line looks like a command and hit enter after each of them. The app showed up in my Applications list, it opens. But its windows is empty, not like the screenshot from the GitHub page.

I have KDE-Connect app on my Android phone. Says no connection. My PC and phone are in the same network.

I think I did something wrong or missed something but I have no idea. Is just copy-paste those command lines are not enough? Should I add something to them or change something in them? I checked dependencies, terminal says I have the newest version for all of them.

**Comment by infuerano** [comment]
I am on the same page as well.. Any help will be appreciated.

**Comment by hannesschulze** [comment]
See https://github.com/hannesschulze/conecto/issues/12#issuecomment-607424726
